[package]
name = "gananayantra-rusting"
version = "0.5.1"
edition = "2021"
description = "A multi-purpose calculator suite including Health, Financial, Math, Advertising, and E-Commerce tools."
license = "MIT"
repository = "https://github.com/LimaniBhavik/gananayantra-rusting"
readme = "README.md"
keywords = ["calculator", "health", "finance", "math", "ecommerce"]
categories = ["science", "command-line-utilities"]

[dependencies]
chrono = "0.4"
